version: '3.8'

services:
  django-web:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: django_core
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  fastapi_service:
    build:
      context: ./notification_ugc_service
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_ugc
    ports:
      - "8001:8001"
    volumes:
      - ./notification_ugc_service:/app
    environment:
      - DJANGO_URL=http://django-web:8000
    restart: unless-stopped


  flask_service:
    build:
      context: ./ugc_flask_service
      dockerfile: Dockerfile.flask
    container_name: flask_ugc
    ports:
      - "8002:8002"
    volumes:
      - ./ugc_flask_service:/app
    environment:
      - DJANGO_URL=http://django-web:8000
      - FASTAPI_URL=http://fastapi_service:8001
    restart: unless-stopped