FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Копируем зависимости FastAPI
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем код микросервиса
COPY . .

EXPOSE 8001

# Запускаем uvicorn с hot-reload
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]